"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
const API_BASE = (process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");
type Task = { id: string; title?: string; status: string; workflow_stage?: string | null; progress?: number; score?: number | null; created_at?: string };
const STATUS_LABEL: Record<string, string> = { pending: "等待处理", analyzing: "文档解析", planning: "格式规划", executing: "自动修改", verifying: "质量验证", running: "处理中", completed: "已完成", failed: "失败", created: "等待处理" };
const WORKFLOW_LABEL: Record<string, string> = { analyzing: "分析中", planning: "规划中", executing: "执行中", verifying: "验证中", completed: "完成", failed: "失败" };
export default function DashboardPage() {
  const router = useRouter(); const [tasks, setTasks] = useState<Task[]>([]); const [error, setError] = useState(""); const [email, setEmail] = useState(""); const [workspace, setWorkspace] = useState("");
  useEffect(() => { const token = localStorage.getItem("paperforge_token"); if (!token) { router.replace("/login"); return; } const savedUser = localStorage.getItem("paperforge_user"); const savedWorkspace = localStorage.getItem("paperforge_workspace"); if (savedUser) setEmail((JSON.parse(savedUser) as { email?: string }).email || ""); if (savedWorkspace) setWorkspace((JSON.parse(savedWorkspace) as { name?: string }).name || ""); fetch(`${API_BASE}/tasks`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error(response.status === 401 ? "登录已过期" : "任务数据加载失败"); setTasks(await response.json() as Task[]); }).catch((reason) => setError(reason instanceof Error ? reason.message : "任务数据加载失败")); }, [router]);
  function logout() { localStorage.removeItem("paperforge_token"); localStorage.removeItem("paperforge_user"); localStorage.removeItem("paperforge_workspace"); router.push("/login"); }
  const completedCount = tasks.filter((task) => task.status === "completed").length; const processingCount = tasks.filter((task) => ["pending", "analyzing", "planning", "executing", "verifying", "running"].includes(task.status)).length;
  return <main className="dashboard-page"><div className="dashboard-header"><div><p className="eyebrow">PAPERFORGE SaaS</p><h1>工作空间 Dashboard</h1><p className="muted-text">{workspace || "PaperForge Workspace"}</p></div><button className="secondary-button" onClick={logout}>退出登录</button></div><section className="dashboard-grid"><article className="dashboard-card"><span className="card-label">当前用户</span><strong>{email || "—"}</strong></article><article className="dashboard-card"><span className="card-label">Workspace</span><strong>{workspace || "—"}</strong></article><article className="dashboard-card"><span className="card-label">总任务数</span><strong>{tasks.length}</strong></article><article className="dashboard-card"><span className="card-label">已完成</span><strong>{completedCount}</strong></article><article className="dashboard-card"><span className="card-label">处理中</span><strong>{processingCount}</strong></article></section>{error && <p className="error-text">{error}</p>}<section className="dashboard-card task-center"><div className="dashboard-section-heading"><div><span className="card-label">最近任务</span><h2>任务中心</h2></div><Link className="dashboard-link" href="/">新建任务 →</Link></div>{tasks.length === 0 ? <p className="muted-text">还没有任务，上传一篇论文开始处理。</p> : <div className="task-list">{tasks.slice(0, 10).map((task) => <Link className="task-row" href={`/tasks/${task.id}`} key={task.id}><span><strong>{task.title || "PaperForge Documents"}</strong><small>{task.created_at ? new Date(task.created_at).toLocaleString("zh-CN") : "—"}</small></span><span className={`task-status task-status-${task.status}`}><b>{STATUS_LABEL[task.status] || task.status}</b>{task.workflow_stage ? ` · ${WORKFLOW_LABEL[task.workflow_stage] || task.workflow_stage}` : task.score === null || task.score === undefined ? "—" : `${task.score} 分`}</span></Link>)}</div>}</section><Link className="dashboard-link" href="/">进入论文处理工作台 →</Link></main>;
}
