"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
const API_BASE = (process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000").replace(/\/+$/, "");
type Artifact = { id: string; file_path: string; file_type: string; download_url?: string }; type WorkflowStep = { key: string; label: string; status: string }; type TraceItem = { state?: string; component?: string; action?: string; status?: string; message?: string; duration_ms?: number };
type Task = { id: string; paper_name?: string; status: string; workflow_stage?: string | null; progress?: number; score?: number | null; score_history?: { before?: number | null; after?: number | null }; trace?: TraceItem[]; workflow_steps?: WorkflowStep[]; artifacts?: Artifact[]; created_at?: string };
const STATUS_LABEL: Record<string, string> = { pending: "等待处理", analyzing: "文档解析", planning: "格式规划", executing: "自动修改", verifying: "质量验证", running: "处理中", completed: "已完成", failed: "失败", created: "等待处理" }; const WORKFLOW_LABEL: Record<string, string> = { analyzing: "分析中", planning: "规划中", executing: "执行中", verifying: "验证中", completed: "完成", failed: "失败" };
export default function TaskDetailPage() {
  const router = useRouter(); const params = useParams<{ taskId: string }>(); const [task, setTask] = useState<Task | null>(null); const [error, setError] = useState("");
  async function downloadArtifact(artifact: Artifact) { const token = localStorage.getItem("paperforge_token"); const response = await fetch(`${API_BASE}${artifact.download_url || ""}`, { headers: { Authorization: `Bearer ${token || ""}` } }); if (!response.ok) { setError("产物下载失败"); return; } const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = artifact.file_path.split(/[\\/]/).pop() || "paperforge-artifact"; link.click(); URL.revokeObjectURL(url); }
  useEffect(() => { const token = localStorage.getItem("paperforge_token"); if (!token) { router.replace("/login"); return; } fetch(`${API_BASE}/tasks/${encodeURIComponent(params.taskId)}`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.detail || "任务加载失败"); setTask(data as Task); }).catch((reason) => setError(reason instanceof Error ? reason.message : "任务加载失败")); }, [params.taskId, router]);
  return <main className="dashboard-page"><Link className="dashboard-link" href="/dashboard">← 返回任务中心</Link><section className="task-detail-shell"><div className="dashboard-card"><p className="eyebrow">TASK DETAIL</p>{error ? <p className="error-text">{error}</p> : !task ? <p className="muted-text">加载中…</p> : <><div className="task-detail-heading"><div><h1>{task.paper_name || "PaperForge 任务"}</h1><p className="muted-text">创建于 {task.created_at ? new Date(task.created_at).toLocaleString("zh-CN") : "—"}</p></div><span className={`task-status task-status-${task.status}`}>{STATUS_LABEL[task.status] || task.status}</span></div><div className="score-change"><span>当前阶段</span><strong>{WORKFLOW_LABEL[task.workflow_stage || ""] || "等待处理"}</strong><small>{typeof task.progress === "number" ? ` · ${task.progress}%` : ""}</small></div><div className="score-change"><span>评分变化</span><strong>{task.score_history?.before ?? "—"} <em>→</em> {task.score_history?.after ?? task.score ?? "—"}</strong></div></>}</div>{task && <><section className="dashboard-card"><div className="dashboard-section-heading"><div><span className="card-label">AGENT WORKFLOW</span><h2>执行流程</h2></div><span className="muted-text">当前阶段：{WORKFLOW_LABEL[task.workflow_stage || ""] || "等待处理"}</span></div><ol className="workflow-timeline">{(task.workflow_steps || []).map((step) => <li className={step.status} key={step.key}><span>{step.status === "completed" ? "✓" : "•"}</span><strong>{step.label}</strong><small>{step.status === "completed" ? "已完成" : step.status === "failed" ? "失败" : step.status === "running" ? "进行中" : "等待"}</small></li>)}</ol></section><section className="dashboard-card"><div className="dashboard-section-heading"><div><span className="card-label">ARTIFACTS</span><h2>交付物</h2></div></div><div className="artifact-grid">{(task.artifacts || []).map((artifact) => <button className="artifact-card" type="button" onClick={() => void downloadArtifact(artifact)} key={artifact.id}><strong>{artifact.file_type === "docx" ? "修改后的 DOCX" : "分析报告"}</strong><small>{artifact.file_type === "docx" ? "下载处理结果" : "下载 JSON 报告"} ↗</small></button>)}</div></section><section className="dashboard-card"><div className="dashboard-section-heading"><div><span className="card-label">TRACE</span><h2>Agent 执行记录</h2></div></div><ol className="trace-list task-trace">{(task.trace || []).map((item, index) => <li className={String(item.status || "").toLowerCase()} key={`${item.action || item.component || "trace"}-${index}`}><div><strong>{item.state || item.component || "Agent"}</strong><small>{item.action || item.message || ""}</small></div><span>{item.duration_ms ? `${item.duration_ms} ms` : String(item.status || "")}</span></li>)}</ol></section></>}</section></main>;
}
